### ISSUE TITLE
To-do-list Not working

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Student-Planner#10] opened 2020-10-15 05:22 UTC
**Summary:**
The to-do list functionality is no longer working. It doesn't register the task that is inputted and display it in the taskboard. There are 2 different implementations of the web app: one with a flask backend, and one with an http.server backend. Both work in terms of logging in and include documentation on how to run. It seems that in both implementations, the script.js file, which includes the functions for getting the form data and displaying it in a task card, is not working and none of the functions are running. 

PS. I don't know if this counts as adding big features but we should stop eventually, as it is technically the end of the sprint. I'm not sure if these are still minor changes or not. We can just update the documentation and record a short demo if this is not a minor change.

**Comment by V2dha** [comment] 2020-10-15 05:32
How can that not be working when It clearly worked on my system's local host. You might have made a mistake kindly check it.
Secondly this is not a big feature this is actually one of the feature that we showed in the demo so we should make it work.

**Comment by sh-biswas** [comment] 2020-10-15 05:35
Did you use the implementations in the branches firebase and flask? Those are the branches we are working from as Emily and I have implemented new backends.

**Comment by V2dha** [comment] 2020-10-15 05:36
Emily merged the todolist branch in the frontend and she worked on it after wards. I just worked on the todolist branch when it wasn't merged.

**Comment by sh-biswas** [comment] 2020-10-15 05:38
Yes, but the functions are yours, right? Emily and I have tried to fix the issue for several hours now so we were wondering if you could take a look and see if you can fix anything we couldn't spot.

**Comment by V2dha** [comment] 2020-10-15 05:41
Yes I am working on it however if the problem is with "POST" method then it had do something with the server backend.

**Comment by V2dha** [comment] 2020-10-15 16:21
The to do list is not working due to the drag and drop feature. Maybe we should scrap that coz we only have two features and as such drag and drop is not needed.

**Closed as completed** 2020-10-15 16:21 UTC
Labels: bug
